# Modelos de recomendações:

##Modelo de recomendação por avaliação:

###Carregando as bases e analisando: 

In [1]:
import pandas as pd

In [2]:
dnc_order_reviews = pd.read_csv('/content/DNC_order_reviews_dataset.csv',index_col=0)
dnc_order_items = pd.read_csv('/content/DNC_order_items_dataset.csv',index_col=0)
dnc_orders = pd.read_csv('/content/DNC_orders_dataset.csv',index_col=0)
dnc_products = pd.read_csv('/content/DNC_products_dataset.csv',index_col=0)

In [3]:
dnc_order_reviews.head()

review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb   
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33   
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b   
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b   
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1   

   review_score  
0             4  
1             5  
2             5  
3             5  
4             5

In [4]:
dnc_order_items.head()

order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   
1  00018f77f2f0320c557190d7a144bdd3              1   
2  000229ec398224ef6ca0657da4fc703e              1   
3  00024acbcdf0a6daa1e931b038114c75              1   
4  00042b26cf59d7ce69dfabb4e55b4fd9              1   

                         product_id   price  
0  4244733e06e7ecb4970a6e2683c13e61   58.90  
1  e5f2d52b802189ee658865ca93d83a8f  239.90  
2  c777355d18b72b67abbeef9df44fd0fd  199.00  
3  7634da152a4610f1595efa32f14722fc   12.99  
4  ac6c3623068f30de03045865e4e10089  199.90

In [5]:
dnc_orders.head()

order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status  
0    delivered  
1    delivered  
2    delivered  
3    delivered  
4    delivered

In [6]:
dnc_products.head()

product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria   
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes   
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer   
3  cef67bcfe19066a932b7673e239eb23d                  bebes   
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas   

   product_name_lenght  product_description_lenght  product_weight_g  \
0                 40.0                       287.0             225.0   
1                 44.0                       276.0            1000.0   
2                 46.0                       250.0             154.0   
3                 27.0                       261.0             371.0   
4                 37.0                       402.0             625.0   

   product_length_cm  product_height_cm  product_width_cm  
0               16.0               10.0              14.0  
1               30.0               18.0              20.0  
2               18.0                9.0              15.0  
3               26.0                4.0              26.0  
4               20.0               17.0              13.0

###Tratamento de nulos, caso presentes:

In [7]:
dnc_order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99224 entries, 0 to 99223
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   review_id     99224 non-null  object
 1   order_id      99224 non-null  object
 2   review_score  99224 non-null  int64 
dtypes: int64(1), object(2)
memory usage: 3.0+ MB


In [8]:
dnc_order_items.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 112650 entries, 0 to 112649
Data columns (total 4 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   order_id       112650 non-null  object 
 1   order_item_id  112650 non-null  int64  
 2   product_id     112650 non-null  object 
 3   price          112650 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 4.3+ MB


In [9]:
dnc_orders.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99441 entries, 0 to 99440
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   order_id      99441 non-null  object
 1   customer_id   99441 non-null  object
 2   order_status  99441 non-null  object
dtypes: object(3)
memory usage: 3.0+ MB


In [10]:
dnc_products.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32951 entries, 0 to 32950
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   product_id                  32951 non-null  object 
 1   product_category_name       32341 non-null  object 
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_weight_g            32949 non-null  float64
 5   product_length_cm           32949 non-null  float64
 6   product_height_cm           32949 non-null  float64
 7   product_width_cm            32949 non-null  float64
dtypes: float64(6), object(2)
memory usage: 2.3+ MB


In [11]:
dnc_products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [12]:
dnc_products = dnc_products.dropna()

In [13]:
df_principal = dnc_orders[dnc_orders['order_status'] == 'delivered']

In [14]:
df_principal = pd.merge(df_principal,dnc_order_reviews, how='inner', on='order_id')

In [15]:
df_principal.head()

order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   

  order_status                         review_id  review_score  
0    delivered  a54f0611adc9ed256b57ede6b6eb5114             4  
1    delivered  8d5266042046a06655c8db133d120ba5             4  
2    delivered  e73b67b67587f7644d5bd1a52deb1b01             5  
3    delivered  359d03e676b3c069f62cadba8dd3f6e8             5  
4    delivered  e50934924e227544ba8246aeb3770dd4             5

In [16]:
df_principal.shape

(96361, 5)

###Montando o dataframe principal com as informações necessárias para o modelo:

In [17]:
dnc_order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'price'], dtype='object')

In [18]:
item_id = dnc_order_items[['order_id','product_id','order_item_id']]

In [19]:
df_principal = pd.merge(df_principal,item_id, how='left', on='order_id')

In [20]:
df_principal.shape

(110013, 7)

In [21]:
df_principal = df_principal.drop_duplicates('order_id')

In [22]:
dnc_products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_weight_g', 'product_length_cm',
       'product_height_cm', 'product_width_cm'],
      dtype='object')

In [23]:
categorias = dnc_products[['product_id', 'product_category_name']]

In [24]:
df_principal = pd.merge(df_principal,categorias, how='left', on='product_id')

In [25]:
df_principal["product_category_name"] = df_principal["product_category_name"].astype('category')

In [26]:
df_principal["cat_codes"] = df_principal["product_category_name"].cat.codes


In [27]:
df_principal

order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   
...                                 ...                               ...   
95827  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00   
95828  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7   
95829  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c   
95830  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1   
95831  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24   

      order_status                         review_id  review_score  \
0        delivered  a54f0611adc9ed256b57ede6b6eb5114             4   
1        delivered  8d5266042046a06655c8db133d120ba5             4   
2        delivered  e73b67b67587f7644d5bd1a52deb1b01             5   
3        delivered  359d03e676b3c069f62cadba8dd3f6e8             5   
4        delivered  e50934924e227544ba8246aeb3770dd4             5   
...            ...                               ...           ...   
95827    delivered  e262b3f92d1ce917aa412a9406cf61a6             5   
95828    delivered  29bb71b2760d0f876dfa178a76bc4734             4   
95829    delivered  371579771219f6db2d830d50805977bb             5   
95830    delivered  8ab6855b9fe9b812cd03a480a25058a1             2   
95831    delivered  dc9c59b4688062c25758c2be4cafc523             5   

                             product_id  order_item_id  \
0      87285b34884572647811a353c7ac498a              1   
1      595fac2a385ac33a80bd5114aec74eb8              1   
2      aa4383b373c6aca5d8797843e5594415              1   
3      d0b61bfb1de832b15ba9d266ca96e5b0              1   
4      65266b2da20d04dbe00c5c2d3bb7859e              1   
...                                 ...            ...   
95827  ac35486adb7b02598c182c2ff2e05254              1   
95828  f1d4ce8c6dd66c47bbaa8c6781c2a923              1   
95829  b80910977a37536adeddd63663f916ad              1   
95830  d1c427060a0f73f6b889a5c7c61f2ac4              1   
95831  006619bbed68b000c8ba3f8725d5409e              1   

        product_category_name  cat_codes  
0       utilidades_domesticas         72  
1                  perfumaria         62  
2                  automotivo          8  
3                    pet_shop         63  
4                   papelaria         59  
...                       ...        ...  
95827            beleza_saude         11  
95828                   bebes          9  
95829      eletrodomesticos_2         29  
95830  informatica_acessorios         44  
95831            beleza_saude         11  

[95832 rows x 9 columns]

In [28]:
df_principal['cat_codes']

0        72
1        62
2         8
3        63
4        59
         ..
95827    11
95828     9
95829    29
95830    44
95831    11
Name: cat_codes, Length: 95832, dtype: int8

In [29]:
df_principal['cat_codes'] = df_principal['cat_codes'].replace(0,73)

In [30]:
df_principal['cat_codes'] = df_principal['cat_codes'].replace(-1,74)

In [31]:
df_principal

order_id                       customer_id  \
0      e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d   
1      53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef   
2      47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089   
3      949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82   
4      ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c   
...                                 ...                               ...   
95827  9c5dedf39a927c1b2549525ed64a053c  39bd1228ee8140590ac3aca26f2dfe00   
95828  63943bddc261676b46f01ca7ac2f7bd8  1fca14ff2861355f6e5f14306ff977a7   
95829  83c1379a015df1e13d02aae0204711ab  1aa71eb042121263aafbe80c1b562c9c   
95830  11c177c8e97725db2631073c19f07b62  b331b74b18dc79bcdf6532d51e1637c1   
95831  66dea50a8b16d9b4dee7af250b4be1a5  edb027a75a1449115f6b43211ae02a24   

      order_status                         review_id  review_score  \
0        delivered  a54f0611adc9ed256b57ede6b6eb5114             4   
1        delivered  8d5266042046a06655c8db133d120ba5             4   
2        delivered  e73b67b67587f7644d5bd1a52deb1b01             5   
3        delivered  359d03e676b3c069f62cadba8dd3f6e8             5   
4        delivered  e50934924e227544ba8246aeb3770dd4             5   
...            ...                               ...           ...   
95827    delivered  e262b3f92d1ce917aa412a9406cf61a6             5   
95828    delivered  29bb71b2760d0f876dfa178a76bc4734             4   
95829    delivered  371579771219f6db2d830d50805977bb             5   
95830    delivered  8ab6855b9fe9b812cd03a480a25058a1             2   
95831    delivered  dc9c59b4688062c25758c2be4cafc523             5   

                             product_id  order_item_id  \
0      87285b34884572647811a353c7ac498a              1   
1      595fac2a385ac33a80bd5114aec74eb8              1   
2      aa4383b373c6aca5d8797843e5594415              1   
3      d0b61bfb1de832b15ba9d266ca96e5b0              1   
4      65266b2da20d04dbe00c5c2d3bb7859e              1   
...                                 ...            ...   
95827  ac35486adb7b02598c182c2ff2e05254              1   
95828  f1d4ce8c6dd66c47bbaa8c6781c2a923              1   
95829  b80910977a37536adeddd63663f916ad              1   
95830  d1c427060a0f73f6b889a5c7c61f2ac4              1   
95831  006619bbed68b000c8ba3f8725d5409e              1   

        product_category_name  cat_codes  
0       utilidades_domesticas         72  
1                  perfumaria         62  
2                  automotivo          8  
3                    pet_shop         63  
4                   papelaria         59  
...                       ...        ...  
95827            beleza_saude         11  
95828                   bebes          9  
95829      eletrodomesticos_2         29  
95830  informatica_acessorios         44  
95831            beleza_saude         11  

[95832 rows x 9 columns]

In [32]:
df_principal = df_principal[['customer_id','product_id', 'review_score','order_id', 'order_status', 'review_id', 'order_item_id', 'product_category_name', 'cat_codes']]

In [33]:
df_principal

customer_id                        product_id  \
0      9ef432eb6251297304e76186b10a928d  87285b34884572647811a353c7ac498a   
1      b0830fb4747a6c6d20dea0b8c802d7ef  595fac2a385ac33a80bd5114aec74eb8   
2      41ce2a54c0b03bf3443c3d931a367089  aa4383b373c6aca5d8797843e5594415   
3      f88197465ea7920adcdbec7375364d82  d0b61bfb1de832b15ba9d266ca96e5b0   
4      8ab97904e6daea8866dbdbc4fb7aad2c  65266b2da20d04dbe00c5c2d3bb7859e   
...                                 ...                               ...   
95827  39bd1228ee8140590ac3aca26f2dfe00  ac35486adb7b02598c182c2ff2e05254   
95828  1fca14ff2861355f6e5f14306ff977a7  f1d4ce8c6dd66c47bbaa8c6781c2a923   
95829  1aa71eb042121263aafbe80c1b562c9c  b80910977a37536adeddd63663f916ad   
95830  b331b74b18dc79bcdf6532d51e1637c1  d1c427060a0f73f6b889a5c7c61f2ac4   
95831  edb027a75a1449115f6b43211ae02a24  006619bbed68b000c8ba3f8725d5409e   

       review_score                          order_id order_status  \
0                 4  e481f51cbdc54678b7cc49136f2d6af7    delivered   
1                 4  53cdb2fc8bc7dce0b6741e2150273451    delivered   
2                 5  47770eb9100c2d0c44946d9cf07ec65d    delivered   
3                 5  949d5b44dbf5de918fe9c16f97b45f8a    delivered   
4                 5  ad21c59c0840e6cb83a9ceb5573f8159    delivered   
...             ...                               ...          ...   
95827             5  9c5dedf39a927c1b2549525ed64a053c    delivered   
95828             4  63943bddc261676b46f01ca7ac2f7bd8    delivered   
95829             5  83c1379a015df1e13d02aae0204711ab    delivered   
95830             2  11c177c8e97725db2631073c19f07b62    delivered   
95831             5  66dea50a8b16d9b4dee7af250b4be1a5    delivered   

                              review_id  order_item_id  \
0      a54f0611adc9ed256b57ede6b6eb5114              1   
1      8d5266042046a06655c8db133d120ba5              1   
2      e73b67b67587f7644d5bd1a52deb1b01              1   
3      359d03e676b3c069f62cadba8dd3f6e8              1   
4      e50934924e227544ba8246aeb3770dd4              1   
...                                 ...            ...   
95827  e262b3f92d1ce917aa412a9406cf61a6              1   
95828  29bb71b2760d0f876dfa178a76bc4734              1   
95829  371579771219f6db2d830d50805977bb              1   
95830  8ab6855b9fe9b812cd03a480a25058a1              1   
95831  dc9c59b4688062c25758c2be4cafc523              1   

        product_category_name  cat_codes  
0       utilidades_domesticas         72  
1                  perfumaria         62  
2                  automotivo          8  
3                    pet_shop         63  
4                   papelaria         59  
...                       ...        ...  
95827            beleza_saude         11  
95828                   bebes          9  
95829      eletrodomesticos_2         29  
95830  informatica_acessorios         44  
95831            beleza_saude         11  

[95832 rows x 9 columns]

In [34]:
df_principal['review_score'].unique()

array([4, 5, 1, 2, 3])

In [35]:
df_principal

customer_id                        product_id  \
0      9ef432eb6251297304e76186b10a928d  87285b34884572647811a353c7ac498a   
1      b0830fb4747a6c6d20dea0b8c802d7ef  595fac2a385ac33a80bd5114aec74eb8   
2      41ce2a54c0b03bf3443c3d931a367089  aa4383b373c6aca5d8797843e5594415   
3      f88197465ea7920adcdbec7375364d82  d0b61bfb1de832b15ba9d266ca96e5b0   
4      8ab97904e6daea8866dbdbc4fb7aad2c  65266b2da20d04dbe00c5c2d3bb7859e   
...                                 ...                               ...   
95827  39bd1228ee8140590ac3aca26f2dfe00  ac35486adb7b02598c182c2ff2e05254   
95828  1fca14ff2861355f6e5f14306ff977a7  f1d4ce8c6dd66c47bbaa8c6781c2a923   
95829  1aa71eb042121263aafbe80c1b562c9c  b80910977a37536adeddd63663f916ad   
95830  b331b74b18dc79bcdf6532d51e1637c1  d1c427060a0f73f6b889a5c7c61f2ac4   
95831  edb027a75a1449115f6b43211ae02a24  006619bbed68b000c8ba3f8725d5409e   

       review_score                          order_id order_status  \
0                 4  e481f51cbdc54678b7cc49136f2d6af7    delivered   
1                 4  53cdb2fc8bc7dce0b6741e2150273451    delivered   
2                 5  47770eb9100c2d0c44946d9cf07ec65d    delivered   
3                 5  949d5b44dbf5de918fe9c16f97b45f8a    delivered   
4                 5  ad21c59c0840e6cb83a9ceb5573f8159    delivered   
...             ...                               ...          ...   
95827             5  9c5dedf39a927c1b2549525ed64a053c    delivered   
95828             4  63943bddc261676b46f01ca7ac2f7bd8    delivered   
95829             5  83c1379a015df1e13d02aae0204711ab    delivered   
95830             2  11c177c8e97725db2631073c19f07b62    delivered   
95831             5  66dea50a8b16d9b4dee7af250b4be1a5    delivered   

                              review_id  order_item_id  \
0      a54f0611adc9ed256b57ede6b6eb5114              1   
1      8d5266042046a06655c8db133d120ba5              1   
2      e73b67b67587f7644d5bd1a52deb1b01              1   
3      359d03e676b3c069f62cadba8dd3f6e8              1   
4      e50934924e227544ba8246aeb3770dd4              1   
...                                 ...            ...   
95827  e262b3f92d1ce917aa412a9406cf61a6              1   
95828  29bb71b2760d0f876dfa178a76bc4734              1   
95829  371579771219f6db2d830d50805977bb              1   
95830  8ab6855b9fe9b812cd03a480a25058a1              1   
95831  dc9c59b4688062c25758c2be4cafc523              1   

        product_category_name  cat_codes  
0       utilidades_domesticas         72  
1                  perfumaria         62  
2                  automotivo          8  
3                    pet_shop         63  
4                   papelaria         59  
...                       ...        ...  
95827            beleza_saude         11  
95828                   bebes          9  
95829      eletrodomesticos_2         29  
95830  informatica_acessorios         44  
95831            beleza_saude         11  

[95832 rows x 9 columns]

In [36]:
df_principal = df_principal.dropna()

In [37]:
df_principal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 94481 entries, 0 to 95831
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   customer_id            94481 non-null  object  
 1   product_id             94481 non-null  object  
 2   review_score           94481 non-null  int64   
 3   order_id               94481 non-null  object  
 4   order_status           94481 non-null  object  
 5   review_id              94481 non-null  object  
 6   order_item_id          94481 non-null  int64   
 7   product_category_name  94481 non-null  category
 8   cat_codes              94481 non-null  int8    
dtypes: category(1), int64(2), int8(1), object(5)
memory usage: 5.9+ MB


In [38]:
df_principal

customer_id                        product_id  \
0      9ef432eb6251297304e76186b10a928d  87285b34884572647811a353c7ac498a   
1      b0830fb4747a6c6d20dea0b8c802d7ef  595fac2a385ac33a80bd5114aec74eb8   
2      41ce2a54c0b03bf3443c3d931a367089  aa4383b373c6aca5d8797843e5594415   
3      f88197465ea7920adcdbec7375364d82  d0b61bfb1de832b15ba9d266ca96e5b0   
4      8ab97904e6daea8866dbdbc4fb7aad2c  65266b2da20d04dbe00c5c2d3bb7859e   
...                                 ...                               ...   
95827  39bd1228ee8140590ac3aca26f2dfe00  ac35486adb7b02598c182c2ff2e05254   
95828  1fca14ff2861355f6e5f14306ff977a7  f1d4ce8c6dd66c47bbaa8c6781c2a923   
95829  1aa71eb042121263aafbe80c1b562c9c  b80910977a37536adeddd63663f916ad   
95830  b331b74b18dc79bcdf6532d51e1637c1  d1c427060a0f73f6b889a5c7c61f2ac4   
95831  edb027a75a1449115f6b43211ae02a24  006619bbed68b000c8ba3f8725d5409e   

       review_score                          order_id order_status  \
0                 4  e481f51cbdc54678b7cc49136f2d6af7    delivered   
1                 4  53cdb2fc8bc7dce0b6741e2150273451    delivered   
2                 5  47770eb9100c2d0c44946d9cf07ec65d    delivered   
3                 5  949d5b44dbf5de918fe9c16f97b45f8a    delivered   
4                 5  ad21c59c0840e6cb83a9ceb5573f8159    delivered   
...             ...                               ...          ...   
95827             5  9c5dedf39a927c1b2549525ed64a053c    delivered   
95828             4  63943bddc261676b46f01ca7ac2f7bd8    delivered   
95829             5  83c1379a015df1e13d02aae0204711ab    delivered   
95830             2  11c177c8e97725db2631073c19f07b62    delivered   
95831             5  66dea50a8b16d9b4dee7af250b4be1a5    delivered   

                              review_id  order_item_id  \
0      a54f0611adc9ed256b57ede6b6eb5114              1   
1      8d5266042046a06655c8db133d120ba5              1   
2      e73b67b67587f7644d5bd1a52deb1b01              1   
3      359d03e676b3c069f62cadba8dd3f6e8              1   
4      e50934924e227544ba8246aeb3770dd4              1   
...                                 ...            ...   
95827  e262b3f92d1ce917aa412a9406cf61a6              1   
95828  29bb71b2760d0f876dfa178a76bc4734              1   
95829  371579771219f6db2d830d50805977bb              1   
95830  8ab6855b9fe9b812cd03a480a25058a1              1   
95831  dc9c59b4688062c25758c2be4cafc523              1   

        product_category_name  cat_codes  
0       utilidades_domesticas         72  
1                  perfumaria         62  
2                  automotivo          8  
3                    pet_shop         63  
4                   papelaria         59  
...                       ...        ...  
95827            beleza_saude         11  
95828                   bebes          9  
95829      eletrodomesticos_2         29  
95830  informatica_acessorios         44  
95831            beleza_saude         11  

[94481 rows x 9 columns]

In [39]:
df_principal.columns

Index(['customer_id', 'product_id', 'review_score', 'order_id', 'order_status',
       'review_id', 'order_item_id', 'product_category_name', 'cat_codes'],
      dtype='object')

###Filtrando o dataframe principal pelo número de avaliações de produtos. Adotamos um limite para analisar somente produtos que foram analisados mais de 10 vezes.

In [41]:
contagem = pd.DataFrame(df_principal['product_id'].value_counts())


In [42]:
contagem = contagem.rename({'product_id':'contagem'},axis=1)

In [43]:
contagem['product_id'] = contagem.index

In [44]:
contagem = contagem.reset_index(drop=True)

In [45]:
df_principal = pd.merge(df_principal,contagem, how = 'left', on='product_id') 

In [46]:
df_selecionados = df_principal[df_principal['contagem']>10]

In [47]:
df_selecionados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37768 entries, 1 to 94479
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   customer_id            37768 non-null  object  
 1   product_id             37768 non-null  object  
 2   review_score           37768 non-null  int64   
 3   order_id               37768 non-null  object  
 4   order_status           37768 non-null  object  
 5   review_id              37768 non-null  object  
 6   order_item_id          37768 non-null  int64   
 7   product_category_name  37768 non-null  category
 8   cat_codes              37768 non-null  int8    
 9   contagem               37768 non-null  int64   
dtypes: category(1), int64(3), int8(1), object(5)
memory usage: 2.7+ MB


### Transposição de linhas(customer_id) em colunas:

In [48]:

pivot_table = df_selecionados.pivot_table(columns='customer_id', index='product_id', values="review_score")

In [49]:
pivot_table

customer_id                       00012a2ce6f8dcda20d059ce98491703  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               NaN   
008cff0e5792219fae03e570f980b330                               NaN   
00baba5b58e274d0332a0c8a0a66f877                               NaN   
00de7f393d962717eeeb2d7131a40dba                               NaN   
013ee64977aaa6b2b25475095162e0e9                               NaN   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               NaN   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               NaN   
ff7fccf8513f360157f0660fe51d1d88                               NaN   
ffa7e0cbe11656d11a117b534bb1db27                               NaN   
ffc9caf33e2d1e9f44e3e06da19085f7                               NaN   

customer_id                       000379cdec625522490c315e70c7a9fb  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               NaN   
008cff0e5792219fae03e570f980b330                               NaN   
00baba5b58e274d0332a0c8a0a66f877                               NaN   
00de7f393d962717eeeb2d7131a40dba                               NaN   
013ee64977aaa6b2b25475095162e0e9                               NaN   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               NaN   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               NaN   
ff7fccf8513f360157f0660fe51d1d88                               NaN   
ffa7e0cbe11656d11a117b534bb1db27                               NaN   
ffc9caf33e2d1e9f44e3e06da19085f7                               NaN   

customer_id                       0004164d20a9e969af783496f3408652  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               NaN   
008cff0e5792219fae03e570f980b330                               NaN   
00baba5b58e274d0332a0c8a0a66f877                               NaN   
00de7f393d962717eeeb2d7131a40dba                               NaN   
013ee64977aaa6b2b25475095162e0e9                               NaN   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               NaN   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               NaN   
ff7fccf8513f360157f0660fe51d1d88                               NaN   
ffa7e0cbe11656d11a117b534bb1db27                               NaN   
ffc9caf33e2d1e9f44e3e06da19085f7                               NaN   

customer_id                       00046a560d407e99b969756e0b10f282  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               NaN   
008cff0e5792219fae03e570f980b330                               NaN   
00baba5b58e274d0332a0c8a0a66f877                               NaN   
00de7f393d962717eeeb2d7131a40dba                               NaN   
013ee64977aaa6b2b25475095162e0e9                               NaN   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               NaN   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               NaN   
ff7fccf8513f360157f0660fe51d1d88                               NaN   
ffa7e0cbe11656d11a117b534bb1db27                               NaN   
ffc9caf33e2d1e9f44e3e06da19085f7                               NaN   

customer_id                       00066ccbe787a588c52bd5ff404590e3  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               NaN   
008cff0e5792219fae03e570f980b330                               NaN   
00baba5b58e274d0332a0c8a0a66f877                               NaN   
00de7f

In [50]:
pivot_table.fillna(0, inplace=True)

In [51]:
pivot_table.shape

(1347, 37768)

In [52]:
pivot_table

customer_id                       00012a2ce6f8dcda20d059ce98491703  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       000379cdec625522490c315e70c7a9fb  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       0004164d20a9e969af783496f3408652  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       00046a560d407e99b969756e0b10f282  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       00066ccbe787a588c52bd5ff404590e3  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f

### Rodando o modelo com o NearestNeighbors:

In [53]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(pivot_table)

In [54]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

###Avaliando as recomendações do modelo para o primeiro cliente:

In [55]:
distances, suggestions = model.kneighbors(pivot_table.iloc[0, :].values.reshape(1, -1))

In [56]:
pivot_table

customer_id                       00012a2ce6f8dcda20d059ce98491703  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       000379cdec625522490c315e70c7a9fb  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       0004164d20a9e969af783496f3408652  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       00046a560d407e99b969756e0b10f282  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

customer_id                       00066ccbe787a588c52bd5ff404590e3  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f

In [57]:
recomendados = []
for i in range(len(suggestions)):
  recomendados= list(pivot_table.index[suggestions[i]])

In [58]:
for prod in recomendados:
  print('Produto:',prod +', da categoria:',df_principal['product_category_name'][df_principal['product_id']==prod].unique()[0])

Produto: 005030ef108f58b46b78116f754d8d38, da categoria: perfumaria
Produto: 6d2fde7d12bb6ff367dbda120ba8828e, da categoria: informatica_acessorios
Produto: 16bf176650a888512655cc94f61860e3, da categoria: relogios_presentes
Produto: cd46a885543f0e169a49f1eb25c04e43, da categoria: informatica_acessorios
Produto: 86ecc269de40ba13205e7beeee12f26f, da categoria: telefonia


#

In [59]:
# Importando pacotes
from surprise import KNNWithMeans
from surprise import Dataset
from surprise import accuracy
from surprise import Reader
import os
from surprise.model_selection import train_test_split
from sklearn.decomposition import TruncatedSVD

In [60]:
df_selecionados

customer_id                        product_id  \
1      b0830fb4747a6c6d20dea0b8c802d7ef  595fac2a385ac33a80bd5114aec74eb8   
4      8ab97904e6daea8866dbdbc4fb7aad2c  65266b2da20d04dbe00c5c2d3bb7859e   
5      503740e9ca751ccdda7ba28e9ab8f608  060cb19345d90064d1015407193c233d   
6      9bdf08b4b3b52b5526ff42d37d47f222  4520766ec412348b8d4caa5e8a18c464   
9      494dded5b201313c64ed7f100595b95c  08574b074924071f4e201e151b152b4e   
...                                 ...                               ...   
94470  7b270ebc87c25c8404348c10ff80a80e  cb92637d91f8267856d2143b6fc7bd9e   
94471  8e1ec396e317ff4c82a03ce16a0c3eb3  595fac2a385ac33a80bd5114aec74eb8   
94474  f01a6bfcc730456317e4081fe0c9940e  9fc063fd34fed29ccc57b7f8e8d03388   
94477  1fca14ff2861355f6e5f14306ff977a7  f1d4ce8c6dd66c47bbaa8c6781c2a923   
94479  b331b74b18dc79bcdf6532d51e1637c1  d1c427060a0f73f6b889a5c7c61f2ac4   

       review_score                          order_id order_status  \
1                 4  53cdb2fc8bc7dce0b6741e2150273451    delivered   
4                 5  ad21c59c0840e6cb83a9ceb5573f8159    delivered   
5                 4  a4591c265e18cb1dcee52889e2d8acc3    delivered   
6                 5  6514b8ad8028c9f2cc2374ded245783f    delivered   
9                 1  e6ce16cb79ec1d90b1da9085a6118aeb    delivered   
...             ...                               ...          ...   
94470             5  c81f74e50f0496fa39716cc77cacd460    delivered   
94471             5  b0f4af5c1b06e24fef510703bfe9f0a6    delivered   
94474             5  aa04ef5214580b06b10e2a378300db44    delivered   
94477             4  63943bddc261676b46f01ca7ac2f7bd8    delivered   
94479             2  11c177c8e97725db2631073c19f07b62    delivered   

                              review_id  order_item_id  \
1      8d5266042046a06655c8db133d120ba5              1   
4      e50934924e227544ba8246aeb3770dd4              1   
5      89b738e70a1ce346db29a20fb2910161              1   
6      07d67dd06ed5f88bef11ef6b464e79ae              1   
9      15898b543726a832d4137fbef5d1d00e              1   
...                                 ...            ...   
94470  a3d2622729772e64544ec5dbc540c640              1   
94471  ede62474f1618961be12678f362dca4a              1   
94474  e8995c053d3db2d9c07407efe7de52dd              1   
94477  29bb71b2760d0f876dfa178a76bc4734              1   
94479  8ab6855b9fe9b812cd03a480a25058a1              1   

        product_category_name  cat_codes  contagem  
1                  perfumaria         62        97  
4                   papelaria         59        31  
5                  automotivo          8        21  
6                  automotivo          8        52  
9          ferramentas_jardim         40        92  
...                       ...        ...       ...  
94470           esporte_lazer         32        15  
94471              perfumaria         62        97  
94474            beleza_saude         11        15  
94477                   bebes          9        16  
94479  informatica_acessorios         44       306  

[37768 rows x 10 columns]

In [61]:
# Lendo o dataset
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df_selecionados,reader)

# Split dos dados
trainset, testset = train_test_split(data, test_size=0.3,random_state=10)

# Criação de um modelo baseado em item (user_based true / false para alternar entre filtragem colaborativa baseada em usuário ou baseada em item)
algo = KNNWithMeans(k=5, sim_options={'user_based': True})
algo.fit(trainset)

# Teste do modelo
test_pred = algo.test(testset)

ValueError: ignored

In [ ]:
get RMSE
print("Item-based Model : Test Set")
accuracy.rmse(test_pred, verbose=True)

Out:
Item-based Model : Test Set 
RMSE: 1.1980

In [ ]:
algo.get_neighbors(1, 10)

Out:
[2, 12, 17, 24, 30, 34, 35, 36, 42, 60]

# Here are the 10 recommended product names
ratings_df.iloc[[2, 12, 17, 24, 30, 34, 35, 36, 42, 60]].index

['B0000531B7', 'B0000CF8T1', 'B0000DC2VI', 'B0000DJT3C', 'B0000T71C6', 'B000100EQ4', 'B00012182G', 'B00014CZP8', 'B00014FT06', 'B00017LEXO']

In [ ]:
def transform_sample(dataf):
  return pd.DataFrame({
      "user": dataf["customer_id"],
      "product": dataf["product_id"],
      "action": dataf["review_score"]})

def start_pipeline(dataf):
    return dataf.copy()

def get_user_counts(dataf):
  return dataf.groupby(by='customer_id', as_index=False) \
    .agg({'product_id': pd.Series.nunique}) \
    .rename(columns={'product_id': 'product_id_count'}) \
    .set_index('customer_id') \
    .sort_values('product_id_count', ascending = False)

def get_book_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(sample_size) \
    .index \
    .tolist()

sample_size = 1000
top_user_ids = df_principal \
  .pipe(start_pipeline) \
  .pipe(get_user_counts) \
  .pipe(get_n_top_values, sample_size)

sample_size = 999
top_products_ids = df_principal \
  .pipe(start_pipeline) \
  .pipe(get_book_counts) \
  .pipe(get_n_top_values, sample_size) 

In [ ]:
matriz_de_relacionamento_book_sampled = df_principal[df_principal["ISBN"].isin(top_book_ids)] \
  .pipe(transform_sample) \
  .pivot_table(index="user", columns="book", values="action").fillna(0)

In [ ]:
matriz_de_relacionamento_book_sampled.T.shape

In [ ]:
cos_item = cosine_similarity(matriz_de_relacionamento_book_sampled.T)

print(cos_item)

In [ ]:
cos_item.shape

## Temos um produto e queremos saber outros produtos que são consumidos por pessoas com consumos similares

In [ ]:
matriz_de_relacionamento_book_sampled.T.index

Index(['000649840X', '002542730X', '0060008032', '0060096195', '006016848X',
       '0060173289', '0060175400', '0060188731', '006019491X', '0060199652',
       ...
       '1573225517', '1573225789', '1573227331', '1573229326', '1573229571',
       '1573229725', '1576737330', '1592400876', '1878424319', '8873122933'],
      dtype='object', name='book', length=999)

In [ ]:
print(cos_item)

[[1.         0.05983705 0.02857749 ... 0.02202635 0.01551346 0.        ]
 [0.05983705 1.         0.01555774 ... 0.02620312 0.         0.        ]
 [0.02857749 0.01555774 1.         ... 0.04822782 0.         0.        ]
 ...
 [0.02202635 0.02620312 0.04822782 ... 1.         0.         0.        ]
 [0.01551346 0.         0.         ... 0.         1.         0.03301185]
 [0.         0.         0.         ... 0.         0.03301185 1.        ]]


In [ ]:
def mostra_n_mais_proximos(id_de_interesse, lista_instanciast, matriz_similaridade, n):
  print(f"Item de interesse: {instancia_de_interesse}")

  assert id_de_interesse in lista_instanciast
  cliente_idx = lista_instanciast.tolist().index(instancia_de_interesse)
  print(f"Item id: {instancia_de_interesse}, tem índice {cliente_idx}")

  closest_10_users = np.argsort(-matriz_similaridade[cliente_idx])[:n]
  print(instancia_de_interesse, closest_10_users)

  for i in zip(lista_instanciast[closest_10_users], matriz_similaridade[cliente_idx][closest_10_users]):
      print(f"Item {i[0]} tem similaridade {i[1]:.2f} com item {instancia_de_interesse}")


lista_instancias = matriz_de_relacionamento_book_sampled.T.index
instancia_de_interesse = lista_instancias[random.randint(0, len(lista_instancias))]

mostra_n_mais_proximos(instancia_de_interesse, lista_instancias, cos_item, 10)

Item de interesse: 0373484003
Item id: 0373484003, tem índice 249
0373484003 [249 246 248 683 247 252 250 682 253 687]
Item 0373484003 tem similaridade 1.00 com item 0373484003
Item 0373243286 tem similaridade 0.33 com item 0373484003
Item 0373483503 tem similaridade 0.20 com item 0373484003
Item 0515128554 tem similaridade 0.18 com item 0373484003
Item 0373244487 tem similaridade 0.18 com item 0373484003
Item 0373484410 tem similaridade 0.16 com item 0373484003
Item 0373484224 tem similaridade 0.16 com item 0373484003
Item 0515128546 tem similaridade 0.15 com item 0373484003
Item 0373484429 tem similaridade 0.14 com item 0373484003
Item 0515132020 tem similaridade 0.14 com item 0373484003


In [243]:
df_principal.columns

Index(['customer_id', 'product_id', 'review_score', 'order_id', 'order_status',
       'review_id', 'order_item_id', 'product_category_name', 'cat_codes',
       'contagem'],
      dtype='object')

In [73]:
df_principal2 = df_principal[['customer_id', 'product_id', 'cat_codes']]

## Modelo 2 - Item mais selem



In [74]:

def start_pipeline(dataf):
    return dataf.copy()

def get_user_counts(dataf):
  return dataf.groupby(by='customer_id', as_index=False) \
    .agg({'product_id': pd.Series.count}) \
    .rename(columns={'product_id': 'product_id_count'}) \
    .set_index('customer_id') \
    .sort_values('product_id_count', ascending = False)

def get_book_counts(dataf):
  return dataf.groupby(by='product_id', as_index=False) \
    .agg({'customer_id': pd.Series.nunique}) \
    .rename(columns={'customer_id': 'customer_id_count'}) \
    .set_index('product_id') \
    .sort_values('customer_id_count', ascending = False)

def get_n_top_values(dataf, n):
  return dataf.head(sample_size) \
    .index \
    .tolist()

sample_size = 10000
top_user_ids = df_principal2 \
  .pipe(start_pipeline) \
  .pipe(get_user_counts) \
  .pipe(get_n_top_values, sample_size)

sample_size = 74
top_products_ids = df_principal2 \
  .pipe(start_pipeline) \
  .pipe(get_book_counts) \
  .pipe(get_n_top_values, sample_size)


In [75]:
def transform_sample(dataf):
  return pd.DataFrame({
      "user": dataf["customer_id"],
      "product": dataf["product_id"],
      "action": dataf["cat_codes"]
  })

In [76]:
matriz_de_relacionamento_book_sampled = df_principal2[df_principal2["product_id"].isin(top_products_ids)] \
  .pipe(transform_sample) \
  .pivot_table(index="user", columns="product", values="action").fillna(0)

In [77]:
matriz_de_relacionamento_book_sampled.T.shape

(74, 10432)

In [269]:
matriz_de_relacionamento_book_sampled[matriz_de_relacionamento_book_sampled['06edb72f1e0c64b14c5b79353f7abea3']>1]

product                           06edb72f1e0c64b14c5b79353f7abea3  \
user                                                                 
04bb960a2876e66f7874886ca00ebb88                              13.0   
0563e58ea5bb08719e7c7016e1d6b800                              13.0   
05838d97b4a3948e120c9fb440374691                              13.0   
0a28710d39c87618a19f30a66d3a70e4                              13.0   
0aee8a6ccf2eafc62eb7beaaa47f4bbf                              13.0   
...                                                            ...   
fac2c2eb0c7413a1173b3d2caced026a                              13.0   
fcb51e77ad11244f17b29d7d3274fb45                              13.0   
fdf606beec86408df71f59988b4dde00                              13.0   
fe88b90bb0bbd4d74fd7312f8608cd9c                              13.0   
ff33ddf6fafd5d38aaa6c0f7385e418f                              13.0   

product                           08574b074924071f4e201e151b152b4e  \
user                                                                 
04bb960a2876e66f7874886ca00ebb88                               0.0   
0563e58ea5bb08719e7c7016e1d6b800                               0.0   
05838d97b4a3948e120c9fb440374691                               0.0   
0a28710d39c87618a19f30a66d3a70e4                               0.0   
0aee8a6ccf2eafc62eb7beaaa47f4bbf                               0.0   
...                                                            ...   
fac2c2eb0c7413a1173b3d2caced026a                               0.0   
fcb51e77ad11244f17b29d7d3274fb45                               0.0   
fdf606beec86408df71f59988b4dde00                               0.0   
fe88b90bb0bbd4d74fd7312f8608cd9c                               0.0   
ff33ddf6fafd5d38aaa6c0f7385e418f                               0.0   

product                           0a57f7d2c983bcf8188589a5fea4a8da  \
user                                                                 
04bb960a2876e66f7874886ca00ebb88                               0.0   
0563e58ea5bb08719e7c7016e1d6b800                               0.0   
05838d97b4a3948e120c9fb440374691                               0.0   
0a28710d39c87618a19f30a66d3a70e4                               0.0   
0aee8a6ccf2eafc62eb7beaaa47f4bbf                               0.0   
...                                                            ...   
fac2c2eb0c7413a1173b3d2caced026a                               0.0   
fcb51e77ad11244f17b29d7d3274fb45                               0.0   
fdf606beec86408df71f59988b4dde00                               0.0   
fe88b90bb0bbd4d74fd7312f8608cd9c                               0.0   
ff33ddf6fafd5d38aaa6c0f7385e418f                               0.0   

product                           0aabfb375647d9738ad0f7b4ea3653b1  \
user                                                                 
04bb960a2876e66f7874886ca00ebb88                               0.0   
0563e58ea5bb08719e7c7016e1d6b800                               0.0   
05838d97b4a3948e120c9fb440374691                               0.0   
0a28710d39c87618a19f30a66d3a70e4                               0.0   
0aee8a6ccf2eafc62eb7beaaa47f4bbf                               0.0   
...                                                            ...   
fac2c2eb0c7413a1173b3d2caced026a                               0.0   
fcb51e77ad11244f17b29d7d3274fb45                               0.0   
fdf606beec86408df71f59988b4dde00                               0.0   
fe88b90bb0bbd4d74fd7312f8608cd9c                               0.0   
ff33ddf6fafd5d38aaa6c0f7385e418f                               0.0   

product                           0bcc3eeca39e1064258aa1e932269894  \
user                                                                 
04bb960a2876e66f7874886ca00ebb88                               0.0   
0563e58ea5bb08719e7c7016e1d6b800                               0.0   
05838d97b4a3948e120c9fb440374691                               0.0   
0a2871

In [274]:
from sklearn.metrics.pairwise import cosine_similarity

cos_item = cosine_similarity(matriz_de_relacionamento_book_sampled.T)

print(cos_item)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [270]:
cos_item

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [273]:
cos_item.T.shape

(10432, 10432)

In [275]:
import numpy as np
import random

def mostra_n_mais_proximos(id_de_interesse, lista_instanciast, matriz_similaridade, n):
  print(f"Item de interesse: {instancia_de_interesse}")

  assert id_de_interesse in lista_instanciast
  cliente_idx = lista_instanciast.tolist().index(instancia_de_interesse)
  print(f"Item id: {instancia_de_interesse}, tem índice {cliente_idx}")

  closest_10_users = np.argsort(-matriz_similaridade[cliente_idx])[:n]
  print(instancia_de_interesse, closest_10_users)

  for i in zip(lista_instanciast[closest_10_users], matriz_similaridade[cliente_idx][closest_10_users]):
      print(f"Item {i[0]} tem similaridade {i[1]:.2f} com item {instancia_de_interesse}")


lista_instancias = matriz_de_relacionamento_book_sampled.T.index
instancia_de_interesse = lista_instancias[random.randint(0, len(lista_instancias))]

mostra_n_mais_proximos(instancia_de_interesse, lista_instancias, cos_item, 10)

Item de interesse: 3fbc0ef745950c7932d5f2a446189725
Item id: 3fbc0ef745950c7932d5f2a446189725, tem índice 16
3fbc0ef745950c7932d5f2a446189725 [16  0 53 52 51 50 49 48 47 46]
Item 3fbc0ef745950c7932d5f2a446189725 tem similaridade 1.00 com item 3fbc0ef745950c7932d5f2a446189725
Item 06edb72f1e0c64b14c5b79353f7abea3 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item aca2eb7d00ea1a7b8ebd4e68314663af tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item a92930c327948861c015c919a0bcb4a8 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item a62e25e09e05e6faf31d90c6ec1aa3d1 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item a50acd33ba7a8da8e9db65094fa990a4 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item 99a4788cb24856965c36a24e339b6058 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item 8c591ab0ca519558779df02023177f44 tem similaridade 0.00 com item 3fbc0ef745950c7932d5f2a446189725
Item 8c292

In [241]:
df_principal[df_principal['product_id']=='2b4609f8948be18874494203496bc318']

customer_id                        product_id  \
19     4fa1cd166fa598be6de80fa84eaade43  2b4609f8948be18874494203496bc318   
126    df5c9e02596851fcbfc98804e4108bbd  2b4609f8948be18874494203496bc318   
262    abd4fba77f31f5efdc766a09851e4da3  2b4609f8948be18874494203496bc318   
730    e1f67a370030c2c5695ee3f95c44cd90  2b4609f8948be18874494203496bc318   
1686   e630c8a8b546a3a6486ccdca9cc6eb0a  2b4609f8948be18874494203496bc318   
...                                 ...                               ...   
92295  804b12a87e551f74f8d1f0c310eeb15b  2b4609f8948be18874494203496bc318   
92516  e061c2ded773c5f33557a5d1fc914d23  2b4609f8948be18874494203496bc318   
92614  23898fe69fc9787b0855955d2d4363ca  2b4609f8948be18874494203496bc318   
92692  bf18d7a165e5587fc4c0255650798092  2b4609f8948be18874494203496bc318   
92987  4ab661c666d14b2b8e1e2dc0986bd23f  2b4609f8948be18874494203496bc318   

       review_score                          order_id order_status  \
19                5  f848643eec1d69395095eb3840d2051e    delivered   
126               1  741fd1b80f015f170a7f458cf86769b8    delivered   
262               5  f93af565de05d2427790ad8d0368a80e    delivered   
730               1  f9f15e02ed74cf8a21b8266a55498942    delivered   
1686              3  c000556923c9e9f96eb1121213f153b0    delivered   
...             ...                               ...          ...   
92295             4  bdc0bd072186ba7097165ec74875f0eb    delivered   
92516             5  ecfedc3b6324cb92d08d241268a15046    delivered   
92614             5  1544b91291000836c72384f035436fbf    delivered   
92692             3  18eed697baafc4ed323ca3e737faaa75    delivered   
92987             5  168098b366e2b3274e4e458f478ac9ba    delivered   

                              review_id  order_item_id product_category_name  \
19     f3d78d82a38fc81f086b0d810edcf3aa              1          beleza_saude   
126    beca43af2351f68ef6067d91a950b9d2              1          beleza_saude   
262    b97473d7ab824a1246b9c0539fdf289d              1          beleza_saude   
730    f5daca55aedc120086c17d08f16c1548              1          beleza_saude   
1686   ebc9c29d8fde23345b7f177b9c89ad65              1          beleza_saude   
...                                 ...            ...                   ...   
92295  e507391aa0b56b81113a38a1ce4b1fd2              1          beleza_saude   
92516  f1f9c577f3005e7d7341349650f451dc              1          beleza_saude   
92614  f7c0fcd3ce8c955703e92898bdf4ffa0              1          beleza_saude   
92692  e6ad2ac2ff923acedeb34a0426a5eccc              1          beleza_saude   
92987  3909c2ecd0282dde08b409c95c3aa53a              1          beleza_saude   

       cat_codes  contagem  
19            11       253  
126           11       253  
262           11       253  
730           11       253  
1686          11       253  
...          ...       ...  
92295         11       253  
92516         11       253  
92614         11       253  
92692         11       253  
92987         11       253  

[253 rows x 10 columns]

In [242]:
df_principal[df_principal['product_id']=='880be32f4db1d9f6e2bec38fb6ac23ab']

customer_id                        product_id  \
263    a9c6cd6cf9583fa5820d55c21238f78e  880be32f4db1d9f6e2bec38fb6ac23ab   
2165   f9835897d532524a6e9686847d4db4a7  880be32f4db1d9f6e2bec38fb6ac23ab   
4742   d3f97856abef8923cb180cca3f197823  880be32f4db1d9f6e2bec38fb6ac23ab   
5333   623de6c1e2801c6702b4f1d70b72777f  880be32f4db1d9f6e2bec38fb6ac23ab   
5488   4415b9cc1e718722dd4bf4a79ccb08e0  880be32f4db1d9f6e2bec38fb6ac23ab   
...                                 ...                               ...   
89748  f7eab7d0e27f9ebe87e9db3c3c01eee3  880be32f4db1d9f6e2bec38fb6ac23ab   
89868  a43420da9f54b35f3bc8e9b201209a76  880be32f4db1d9f6e2bec38fb6ac23ab   
91292  c532bde5e3c7e9665dd16a0ff0d084b2  880be32f4db1d9f6e2bec38fb6ac23ab   
91569  743c9c1929ea99b6885d5a43501307cc  880be32f4db1d9f6e2bec38fb6ac23ab   
93618  da58a1b4746c306cd736bec85eb02118  880be32f4db1d9f6e2bec38fb6ac23ab   

       review_score                          order_id order_status  \
263               5  3f3913e8c7fd221ac82a34ffa20b93ee    delivered   
2165              5  ff8780cfb4535054cc5b56046b170cc0    delivered   
4742              5  30207f5d26e6ca2cb7ef1b25fa2585cc    delivered   
5333              5  eb8871f7b0a4b2678e414a280b52349b    delivered   
5488              5  98826cd8a97e41725b525e492a8d7571    delivered   
...             ...                               ...          ...   
89748             5  beea8116a9908f0390812fd77d9b1f2e    delivered   
89868             5  d6c897633f14d2c71e22c530ae9f0a11    delivered   
91292             3  7f0b2d90543efaf906caac20ff4ed83f    delivered   
91569             5  f813aba63e668c603b5e723e0f8f7bad    delivered   
93618             5  c4ee850f0510c341d498f4d7adbd7540    delivered   

                              review_id  order_item_id product_category_name  \
263    196a0fa170671c3d3759002b85643f00              1            brinquedos   
2165   ff4c0add3cb34239b9f030861bfaf846              1            brinquedos   
4742   9913421a75ed1b68a70682866895f202              1            brinquedos   
5333   3d543cb9998654961aef96f93cab16a6              1            brinquedos   
5488   921e94286c880284401ec0922e973a0a              1            brinquedos   
...                                 ...            ...                   ...   
89748  f89a3ef4753a2c23b51caf8b419cf588              1            brinquedos   
89868  bf6afcb8a89db355056402015a0070ef              1            brinquedos   
91292  897801fa573a67de993f9a213b643bab              1            brinquedos   
91569  4c57b9d34f61cc165e52858e2cad3886              1            brinquedos   
93618  cc463b4ca5e5fe404166ab14b7726667              1            brinquedos   

       cat_codes  contagem  
263           12        92  
2165          12        92  
4742          12        92  
5333          12        92  
5488          12        92  
...          ...       ...  
89748         12        92  
89868         12        92  
91292         12        92  
91569         12        92  
93618         12        92  

[92 rows x 10 columns]

In [62]:
pivot_table = df_selecionados.pivot_table(columns='review_id', index='product_id', values="review_score")

In [63]:
pivot_table.fillna(0, inplace=True)

In [93]:
pivot_table

review_id                         0001239bc1de2e33cb583967c2ca4c67  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

review_id                         00020c7512a52e92212f12d3e37513c0  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

review_id                         00032b0141443497c898b3093690af51  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

review_id                         00034d88989f9a4c393bdcaec301537f  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f393d962717eeeb2d7131a40dba                               0.0   
013ee64977aaa6b2b25475095162e0e9                               0.0   
...                                                            ...   
fed5c40c27e1c88560a9e92d82ee0825                               0.0   
ff29d8cb1cd0cd5ea37b80dac9939e1c                               0.0   
ff7fccf8513f360157f0660fe51d1d88                               0.0   
ffa7e0cbe11656d11a117b534bb1db27                               0.0   
ffc9caf33e2d1e9f44e3e06da19085f7                               0.0   

review_id                         000359bceee1b6fe876b30d35b5f9ef2  \
product_id                                                           
005030ef108f58b46b78116f754d8d38                               0.0   
008cff0e5792219fae03e570f980b330                               0.0   
00baba5b58e274d0332a0c8a0a66f877                               0.0   
00de7f

In [94]:
from sklearn.metrics.pairwise import cosine_similarity

cos_item = cosine_similarity(pivot_table)

print(cos_item)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [95]:
cos_item

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [68]:
cos_item.T.shape

(1347, 1347)

In [92]:
import numpy as np
import random

def mostra_n_mais_proximos(id_de_interesse, lista_instanciast, matriz_similaridade, n):
  print(f"Item de interesse: {instancia_de_interesse}")

  assert id_de_interesse in lista_instanciast
  cliente_idx = lista_instanciast.tolist().index(instancia_de_interesse)
  print(f"Item id: {instancia_de_interesse}, tem índice {cliente_idx}")

  closest_10_users = np.argsort(-matriz_similaridade[cliente_idx])[:n]
  print(instancia_de_interesse, closest_10_users)
  return lista_instanciast[closest_10_users].tolist() 


lista_instancias = matriz_de_relacionamento_book_sampled
instancia_de_interesse = lista_instancias[random.randint(0, len(lista_instancias))]

lista = mostra_n_mais_proximos(instancia_de_interesse, lista_instancias, cos_item, 10)

KeyError: ignored

In [87]:
for 

Index(['06edb72f1e0c64b14c5b79353f7abea3', '08574b074924071f4e201e151b152b4e',
       '0a57f7d2c983bcf8188589a5fea4a8da', '0aabfb375647d9738ad0f7b4ea3653b1',
       '0bcc3eeca39e1064258aa1e932269894', '154e7e31ebfa092203795c972e5804a6',
       '165f86fe8b799a708a20ee4ba125c289', '19c91ef95d509ea33eda93495c4d3481',
       '2028bf1b01cafb2d2b1901fca4083222', '29427de7f8a9ee983d9dbc51cec569b4',
       '2b4609f8948be18874494203496bc318', '35afc973633aaeb6b877ff57b2793310',
       '368c6c730842d78016ad823897a372db', '36f60d45225e60c7da4558b070ce4b60',
       '389d119b48cf3043d311335e499d9c6b', '3dd2a17168ec895c781a9191c1e95ad7',
       '3fbc0ef745950c7932d5f2a446189725', '422879e10f46682990de24d770e7f83d',
       '42a2c92a0979a949ca4ea89ec5c7b934', '43423cdffde7fda63d0414ed38c11a73',
       '437c05a395e9e47f9762e677a7068ce7', '461f43be3bdf8844e65b62d9ac2c7a5a',
       '473795a355d29305c3ea6b156833adf5', '4c2394abfbac7ff59ec7a420918562fa',
       '4fcb3d9a5f4871e8362dfedbdb02b064', '4fe644d7

In [83]:
lista_instancias

Index(['06edb72f1e0c64b14c5b79353f7abea3', '08574b074924071f4e201e151b152b4e',
       '0a57f7d2c983bcf8188589a5fea4a8da', '0aabfb375647d9738ad0f7b4ea3653b1',
       '0bcc3eeca39e1064258aa1e932269894', '154e7e31ebfa092203795c972e5804a6',
       '165f86fe8b799a708a20ee4ba125c289', '19c91ef95d509ea33eda93495c4d3481',
       '2028bf1b01cafb2d2b1901fca4083222', '29427de7f8a9ee983d9dbc51cec569b4',
       '2b4609f8948be18874494203496bc318', '35afc973633aaeb6b877ff57b2793310',
       '368c6c730842d78016ad823897a372db', '36f60d45225e60c7da4558b070ce4b60',
       '389d119b48cf3043d311335e499d9c6b', '3dd2a17168ec895c781a9191c1e95ad7',
       '3fbc0ef745950c7932d5f2a446189725', '422879e10f46682990de24d770e7f83d',
       '42a2c92a0979a949ca4ea89ec5c7b934', '43423cdffde7fda63d0414ed38c11a73',
       '437c05a395e9e47f9762e677a7068ce7', '461f43be3bdf8844e65b62d9ac2c7a5a',
       '473795a355d29305c3ea6b156833adf5', '4c2394abfbac7ff59ec7a420918562fa',
       '4fcb3d9a5f4871e8362dfedbdb02b064', '4fe644d7

In [82]:
len(list(instancia_de_interesse))

32

In [84]:
instancia_de_interesse

'42a2c92a0979a949ca4ea89ec5c7b934'